config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'invoices#index'

  resources :invoices do 
    resources :payments, only: [:new, :create, :show, :edit, :update]
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	validates :amount, :presence => :true
	has_one :payment

  def self.to_csv(options = {})
    CSV.generate do |csv|
      csv << column_names
      all.each do |invoice|
        csv << invoice.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	validates :amount, :presence => :true
	belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]


  def index
    @invoices = Invoice.all
    respond_to do |format|
      format.html
      format.json { render json: @invoices.to_json }
      format.csv { render text: @invoices.to_csv }
      format.xls do
        only_columns = [:number, :amount, :date, :to_address, :from_address, :notes]
        send_data @invoices.to_xls(:only => only_columns)
      end
    end
  end


  def show
  end


  def new
    @invoice = Invoice.new
  end

  def edit
  end


  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:number, :amount, :date, :to_address, :from_address, :notes)
    end
    def json_request?
      request.format.json?
    end
end
#http://railscasts.com/episodes/362-exporting-csv-and-excel?view=asciicast

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end
  def new
    @invoice = Invoice.find(params[:invoice_id])
    @payment = @invoice.build_payment
  end

  def create
   @invoice = Invoice.find(params[:invoice_id])
   @payment = @invoice.build_payment(payment_params)
    respond_to do |format|
      if @payment.save
        format.html { redirect_to invoice_payment_path(:invoice_id => @invoice.id, :id => @payment.id), notice: 'payment was  successfully created.' }
        #format.json { render json: @payment, status: :created, payment: @payment }
      else
        format.html { render action: "new" }
        #format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @payment = Payment.find(params[:id])
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:invoice_id])
    @payment = @invoice.payment
    respond_to do |format|
      if @invoice.payment.update(payment_params)
        format.html { redirect_to invoice_payment_path(:invoice_id => @invoice.id, :id => @invoice.payment.id), notice: 'payment was  successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  private
  def payment_params
    params.require(:payment).permit(:amount, :date, :invoice_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_converted_amount(amount)
    require 'converter'
    conv = Converter.new(amount)
    conv.convert!
  end
	def layout_by_resource
		if devise_controller? && resource_name == :user && action_name == 'sign_in'
		  "devise"
		else
		  "application"
		end
    binding.pry
		if current_user.blank? 
			link_to 'Log out', "destroy_user_session_path", :method => "DELETE"
		end
	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/invoices/_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <!-- Theme Made By www.w3schools.com - No Copyright
    -->
    <title>Bootstrap Theme Company Page</title>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"></link>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <br/>
    <div class="container">
      <div class="row">
        <%= form_for(@invoice) do |f| %>
          <% if @invoice.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@invoice.errors.count, "error") %>
                prohibited this invoice from being saved:
              </h2>
              <ul>
                <% @invoice.errors.full_messages.each do |message| %>
                  <li>
                    <%= message %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :number %>
            <br/>
            <%= f.number_field :number, placeholder: 'Select Number)'%>
          </div>
          <div class="field">
            <%= f.label "Amount (USD)" %>
            <br/>
            <%= f.text_field :amount, placeholder: 'Enter amount (USD)' %>
          </div>
          <div class="field">
            <%= f.label :date %>
            <br/>
            <%= f.date_select :date %>
          </div>
          <div class="field">
            <%= f.label :to_address %>
            <br/>
            <%= f.text_field :to_address, placeholder: 'Enter To address' %>
          </div>
          <div class="field">
            <%= f.label :from_address %>
            <br/>
            <%= f.text_field :from_address, placeholder: 'Enter From Address' %>
          </div>
          <div class="field">
            <%= f.label :notes %>
            <br/>
            <%= f.text_field :notes, placeholder: 'Enter Notes' %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/invoices/edit.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>

  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 </head><br>
  <div class="container">
    <div class="row"><br>
     <h1>Edit Invoice </h1>

    <%= render 'form' %>

    <%= link_to 'Back', invoices_path %>
  </div>
 </div>

app/views/invoices/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head><br>
<div class="container">
  <div class="row"><br>

  <p id="notice"><%= notice %></p>

  <h1>Listing Invoices</h1>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Number</th>
        <th>Amount(GBP)</th>
        <th>Date</th>
        <th>To address</th>
        <th>From address</th>
        <th>Notes</th>
        <th colspan="4">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.number %></td>
          <td><%= get_converted_amount(invoice.amount.to_f) %></td>
          <td><%= invoice.date %></td>
          <td><%= invoice.to_address %></td>
          <td><%= invoice.from_address %></td>
          <td><%= invoice.notes %></td>
          <td><%= link_to 'payment', invoice.payment.present? ? invoice_payment_path(invoice, :id => invoice.payment.id) : new_invoice_payment_path(invoice) %></td>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Invoice', new_invoice_path %>

  </div>
</div>
<p>
  Download:
  <%= link_to "CSV", invoices_path(format: "csv") %> |
  <%= link_to "Excel", invoices_path(format: "xls") %>
</p>

app/views/invoices/new.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>

  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 </head><br>
  <div class="container">
    <div class="row"><br>
		 <h1>New Invoice </h1>

		<%= render 'form' %>

		<%= link_to 'Back', invoices_path %>
  </div>
 </div>

app/views/invoices/sample.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Number</Data></Cell>
        <Cell><Data ss:Type="String">Amount(GBP)</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">To address</Data></Cell>
        <Cell><Data ss:Type="String">From address</Data></Cell>
        <Cell><Data ss:Type="String">Notes</Data></Cell>
      </Row>
    <% @invoices.each do |invoice| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= invoice.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= invoice.number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_converted_amount(invoice.amount.to_f) %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= invoice.date %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= invoice.to_address %></Data></Cell>
        <Cell><Data ss:Type="Number"><%=invoice.from_address %></Data></Cell>
        <Cell><Data ss:Type="Number"><%=invoice.notes %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/invoices/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<div class="container">
  <div class="row"><br>
    <div class="container">
      <div class="row"><br>
          <p id="notice"><%= notice %></p>

          <p>
            <strong>Number:</strong>
            <%= @invoice.number %>
          </p>

          <p>
            <strong>Amount:</strong>
            <%= @invoice.amount %>
          </p>

          <p>
            <strong>Date:</strong>
            <%= @invoice.date %>
          </p>

          <p>
            <strong>To address:</strong>
            <%= @invoice.to_address %>
          </p>

          <p>
            <strong>From address:</strong>
            <%= @invoice.from_address %>
          </p>

          <p>
            <strong>Notes:</strong>
            <%= @invoice.notes %>
          </p>

          <%= link_to 'Edit', edit_invoice_path(@invoice) %> |
          <%= link_to 'Back', invoices_path %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if current_user.present? %> 
	<%= link_to 'Log out', destroy_user_session_path, :method => "DELETE" %>
	<%= "Signed In as #{current_user.email}" %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/_form.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 </head><br>
  <div class="container">
  <div class="row"><br>
    <%= form_for ([@payment.invoice, @payment]) do |f| %>
    <% if @payment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
     
        <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
        <%= f.label "amount (USD)" %><br>
        <%= f.text_field :amount, placeholder: 'Enter amount (USD)' %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
      <div class="field">
        <%= f.label :invoice_id %><br>
        <%= f.text_field :invoice_id %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
 </div>

app/views/payments/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Theme Made By www.w3schools.com - No Copyright -->
<title>Bootstrap Theme Company Page</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head><br>
<div class="container">
<div class="row"><br>
	<h1>Edit Payment</h1>
	<%= render 'form' %>
  </div>
</div>

app/views/payments/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Theme Made By www.w3schools.com - No Copyright -->
	<title>Bootstrap Theme Company Page</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head><br>
<div class="container">
<div class="row"><br>
	<h1>New Payment</h1>

	<%= render 'form' %>

  </div>
</div>

app/views/payments/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <!-- Theme Made By www.w3schools.com - No Copyright
    -->
    <title>Bootstrap Theme Company Page</title>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">/</link>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <br/>
        <div class="container">
          <div class="row">
            <br/>
            <p id="notice">
              <%= notice %>
            </p>
            <p>
              <strong>Amount:</strong>
              <%= get_converted_amount(@payment.amount.to_f) %>
            </p>
            <p>
              <strong>Date:</strong>
              <%= @payment.date %>
            </p>
            <p>
              <strong>Invoice Id:</strong>
              <%= @payment.invoice_id %>
            </p>
            <%= link_to 'Back', invoices_path %>
            <%= link_to 'Edit payment', edit_invoice_payment_path(:invoice_id => @payment.invoice.id, :id => @payment.id) %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>